sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhisheksinha08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhisheksinha08/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-web"
  env: "Dockerreactweb-env"
  bucket_name: "elasticbeanstalk-ap-south-1-406904461358"
  bucket_path: "docker-react-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY