sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhisheksinha08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhisheksinha08/docker-react npm run test